# Generated by Django 4.2.1 on 2023-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Монета')),
                ('code', models.CharField(editable=False, max_length=5, verbose_name='Код')),
                ('card', models.TextField(verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Способ оплаты (криптовалюта)',
                'verbose_name_plural': 'Способы оплаты (криптовалюта)',
            },
        ),
    ]
