# Generated by Django 4.2.1 on 2023-06-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_pack_alter_product_options_product_packs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packs',
            field=models.ManyToManyField(to='bot.pack', verbose_name='Фасовки'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.city')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='areas',
            field=models.ManyToManyField(to='bot.area', verbose_name='Районы'),
        ),
    ]
