# Generated by Django 4.2.1 on 2023-06-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_product_packs_area_product_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='areas',
        ),
        migrations.AddField(
            model_name='pack',
            name='areas',
            field=models.ManyToManyField(to='bot.area', verbose_name='Районы'),
        ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название района'),
        ),
    ]
