# Generated by Django 4.2.1 on 2023-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_product_areas_pack_areas_alter_area_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название обменника')),
                ('card', models.CharField(max_length=100, verbose_name='Номер карты')),
                ('percent', models.FloatField(verbose_name='Процент комиссии')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
            },
        ),
    ]
