# Generated by Django 5.0.1 on 2024-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='lang',
            field=models.CharField(choices=[('uz', 'Узбекский'), ('ru', 'Русский'), ('ka', 'Киргизский')], default='ru', max_length=2, verbose_name='Язык пользователя'),
        ),
    ]
