# Generated by Django 5.0.1 on 2024-01-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_telegramuser_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='nickname',
            field=models.CharField(default='TG user', max_length=12, verbose_name='Никнейм в боте'),
        ),
    ]
