# Generated by Django 5.0.1 on 2024-01-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_telegramuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count_of_stars',
            field=models.IntegerField(default=5),
        ),
    ]
