# Generated by Django 5.0.1 on 2024-01-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_comment_count_of_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name_of_product',
            field=models.CharField(max_length=150, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='count_of_stars',
            field=models.IntegerField(default=5, verbose_name='Количество звёзд'),
        ),
    ]
