# Generated by Django 5.0.1 on 2024-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_of_buy',
            field=models.TextField(default='50+', verbose_name='Количество покупок'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default='5.0', verbose_name='Рейтинг'),
        ),
    ]
