# Generated by Django 5.0.1 on 2024-01-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_product_count_of_buy_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freshness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discount', models.FloatField(default=0, verbose_name='Скидка в процентах')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='freshness',
            field=models.ManyToManyField(to='bot.freshness', verbose_name='Свежесть'),
        ),
    ]
