# Generated by Django 5.0.1 on 2024-01-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_freshness_product_freshness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freshness',
            options={'verbose_name': 'Свежесть', 'verbose_name_plural': 'Свежести'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='freshness',
        ),
        migrations.AddField(
            model_name='pack',
            name='freshness',
            field=models.ManyToManyField(to='bot.freshness', verbose_name='Свежесть'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
