# Generated by Django 5.0.1 on 2024-01-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_freshness_options_remove_product_freshness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Тип клада',
                'verbose_name_plural': 'Типы кладов',
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='type_of_buy',
            field=models.ManyToManyField(to='bot.typeofbuy', verbose_name='Тип клада'),
        ),
    ]
